C_Practice: include/recurse.h File Reference
recurse.h File Reference
Functions
int factorial (int factor)
int arithmetic (int factor)
int different_arithmetic (int factor)
int fibonacci (int sum)
int euclidean_division (int a, int b)
Function Documentation
arithmetic()
int arithmetic (int factor)
This function is calculating arithmetic series ...
Parameters
The last terms
Returns
Result
Description: 1 + 2 + 3 + 4 + 5 ....
 {
     if(factor == 1)
         return 1;
     // decreasing
     return( factor + arithmetic(factor - 1));
 }
Referenced by arithmetic(), and different_arithmetic().
different_arithmetic()
int different_arithmetic (int factor)
This function is calculating the different arithmetic series...
Parameters
The last terms
Returns
Result
Description: 1 - 2 + 3 - 4 + 5 - 6 ....
 {
     if(factor == 1)
         return 1;
     // determine the term position
     factor = (factor%2 == 0) ? -factor:factor;
     return( factor + arithmetic(factor - 1));
 }
euclidean_division()
int euclidean_division (int a, int b)
This function is calculating the GCD of two integers by Euclidean algorithm...
Parameters
integer 1
integer 2
Returns
GCD
Idea:
GCD(A,0) = A and GCD(B,0) = B
If A = B⋅Q + R and B≠0 then GCD(A,B) = GCD(B,R) where Q is an integer, R is an integer between 0 and B-1
 {
     if(a%b == 0)
         return 1;
     else
         return euclidean_division(b, a%b);
 }
Referenced by euclidean_division().
factorial()
int factorial (int N)
This function is calculating N factorial ...
Parameters
The times of factorial
Returns
Result
Description: N! = 1 * 2 * 3 * 4 * 5 .... * N
 {
     if (N == 1)
         return 1;
     // decreasing
     return (N*factorial(N-1));
 }
Referenced by factorial().
fibonacci()
int fibonacci (int sum)
This function is calculating the Fibonacci number...
Parameters
The last terms
Returns
Result
Description: 0, 1, 1 ,2, 3, 5 .....
 {
     if (sum == 1)
         return 0;
     else if(sum == 2 | sum == 3)
         return 1;
     else {
         // decreasing
         return (fibonacci(sum-1) + fibonacci(sum-2));
     }
 }
Referenced by fibonacci().